### ISSUE TITLE
4: Window impact not working in example file

### ISSUE THREAD

**Issue by ncatunda** [Bombyx-ETH/Bombyx2#6]
Hi @pedrammrbn 

Not sure if you are still working on Bombyx, but I was having a look at it for HSLU and I just downloaded the version from 29.10.2024 and the window impact component seems not to be working. 

Also there are two components that are broken in this script. At least for me. I'm currently using Rhino Version 8 SR13 (8.13.24289.13001, 2024-10-15). We could have a call and have a look at them together if you want.

![image](https://github.com/user-attachments/assets/0cdeda65-3bdd-43ed-a516-11bec35b881e)

**Comment by pedrammrbn** [comment]
Hi @ncatunda, as a quick fix, you can delete the two "Frame Material" and "Glazing Material" inputs and retrigger the "Activate" input to generate new lists. 

The error is because the example file is not yet updated to match the new version, and the list in the file is from the previous one - should be ready in a couple of days!

**Comment by pedrammrbn** [comment]
If there is any other feedback from using the plugin at HSLU or the fix didn't manage to take care of it, I'd be happy to hop on a call as well!

**Comment by ncatunda** [comment]
Got it! That worked well :) 
Thank you!!

The other thing is that probably this python function is probably outdated as well, but that is something I can update it myself 

![image](https://github.com/user-attachments/assets/86f01af4-ddd9-4756-9d72-95676783db7e)

I'm planning to connect this definition with the materials in a ladybug simulation (similar to the connection with the hive), since Bombyx provides with the U-values as well. I can keep you in the loop if you want. And thanks again for the super quick reply! 

If things works well maybe we could have it available here for next semesters and anyone interested.

**Comment by pedrammrbn** [comment]
Great to hear that!
We're preparing the new Rhino8 example file (the one that will be ready in a few days), so just to save you some work you could wait for that one on Food4Rhino - I'll ping you once it's out.

And please do keep us posted. HB-integration was something we were also considering but did not have the time for, so it would be nice to see how it works.

Let's keep in touch!

**Comment by ncatunda** [comment]
I will wait, thank you. I will start working on connecting the definitions next Saturday on a train ride, so I'm hoping it is enough time by then to get the new example file 👯 
 
I will close the issue, so it doesn't stay hanging around using your brain power in the background haha. 
Comment to close the issue -> The issue is solved with retriggering the button to generate new lists for materials
